spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_pr1
    username: spring_root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true